INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Gorete Medeiros','Rua das Antas 804','7A','goretinha@getmail.com','46984712570');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Carlos Souza','Avenida Brasil 1020','8B','carlossouza@mail.com','46984712671');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Ana Paula','Rua das Flores 456','7A','anapaula@flower.com','46984712782');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Marcos Vinicius','Rua dos Ipês 789','6C','marcosv@vinicius.com','46984712893');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Beatriz Silva','Avenida Central 300','8A','beasilva@mail.com','46984712904');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('João Oliveira','Rua do Sol 150','9B','joao_oliveira@sunmail.com','46984713015');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Fernanda Lima','Rua da Alegria 201','7C','fernanda.lima@joymail.com','46984713126');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Gabriel Santos','Avenida Paulista 1010','6A','gabriel.santos@paulmail.com','46984713237');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Mariana Costa','Rua dos Pinheiros 345','8B','marianacosta@pinheiros.com','46984713348');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Ricardo Pereira','Avenida dos Estados 765','9A','ricardo.pereira@states.com','46984713459');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Letícia Ferreira','Rua das Palmeiras 876','7A','leticia.ferreira@palmmail.com','46984713560');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Fábio Carvalho','Avenida Independência 1234','8C','fabio.carvalho@indepmail.com','46984713671');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Juliana Andrade','Rua Nova 432','6B','juliana.andrade@newmail.com','46984713782');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Thiago Rodrigues','Avenida das Nações 654','9B','thiago.rodrigues@nationmail.com','46984713893');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Larissa Almeida','Rua da Paz 789','8A','larissa.almeida@peace.com','46984713904');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Rafael Mendes','Avenida do Contorno 910','7C','rafael.mendes@contornomail.com','46984714015');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Patrícia Moraes','Rua das Acácias 321','6A','patricia.moraes@acacias.com','46984714126');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Bruno Vieira','Avenida Atlântica 567','8B','bruno.vieira@atlanticmail.com','46984714237');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Camila Barbosa','Rua das Rosas 888','9C','camila.barbosa@roses.com','46984714348');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Rodrigo Alves','Avenida Beira Mar 135','7B','rodrigo.alves@beiramar.com','46984714459');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Sabrina Souza','Rua do Campo 456','8A','sabrina.souza@fieldmail.com','46984714560');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Marcelo Ribeiro','Avenida Getúlio Vargas 678','9A','marcelo.ribeiro@vargas.com','46984714671');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Clara Fernandes','Rua da Lua 901','6C','clara.fernandes@moonmail.com','46984714782');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Daniel Martins','Avenida Ipiranga 101','8B','daniel.martins@ipirangamail.com','46984714893');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Helena Santos','Rua dos Lírios 345','7A','helena.santos@lilymail.com','46984714904');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Lucas Araujo','Avenida das Américas 567','9B','lucas.araujo@americas.com','46984715015');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Amanda Correia','Rua do Prado 789','8C','amanda.correia@pradomail.com','46984715126');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Pedro Costa','Avenida Sete de Setembro 123','6A','pedro.costa@setembromail.com','46984715237');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Isabela Oliveira','Rua das Esmeraldas 456','7B','isabela.oliveira@emeraldsmail.com','46984715348');
INSERT INTO tb_student(name, address, class_name, email, phone) VALUES ('Eduardo Lima','Avenida Rio Branco 789','9A','eduardo.lima@riobrancomail.com','46984715459');
